config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/dashboard' => 'welcome#dashboard', as: :dashboard
  
  resources :users do
    member do
      get 'reset_password', as: :reset_password
      patch 'reset_password' => 'users#update_password'
    end
  end
  resources :payment_methods
  resources :transactions

  get '/login' => 'sessions#new', as: :login
  post '/sessions' => 'sessions#create'

  delete '/logout' => 'sessions#destroy', as: :logout

end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :bank, presence: true
  validates :last_four_digits, length: { is: 4 }
  validates_numericality_of :last_four_digits
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :authenticate
  before_action :authorize_payment_method, only: [:show, :edit]

  def index
    # List only payment method of this user
    @payment_methods = current_user.payment_methods
  end

  def show
    @payment_method = PaymentMethod.find(params[:id])
  end

  def new
    @payment_method = PaymentMethod.new
  end

  def create
    @payment_method = PaymentMethod.new(payment_method_params)
    @payment_method.user = current_user

    if @payment_method.save
      flash[:success] = "You have successfully added a new card"
      redirect_to payment_methods_path
    else
      flash[:danger] = "Please ensure the fields are filled in correctly"
      redirect_to new_payment_method_path
    end
  end

  def edit
    @payment_method = PaymentMethod.find(params[:id])
    
    if @payment_method.payment_type == 'Cash'
      flash[:danger] = "Cannot modify cash payment method"
      redirect_to payment_methods_path
    end
  end

  def update
    @payment_method = PaymentMethod.find(params[:id])
    if @payment_method.update(payment_method_params)
      flash[:success] = "Card #{@payment_method.bank} #{@payment_method.last_four_digits} updated successfully"
      redirect_to payment_method_path(@payment_method)
    else
      flash[:danger] = "Please ensure all fields are filled in correctly"
      redirect_to edit_payment_method_path(@payment_method)
    end
  end

  def destroy
    @payment_method = PaymentMethod.find(params[:id])

    if @payment_method.payment_type == "Cash"
      flash[:danger] = "Cannot delete cash payment method"
      redirect_to payment_methods_path and return
    end

    if @payment_method.destroy
      flash[:warning] = "Card #{@payment_method.bank} #{@payment_method.last_four_digits} has been successfully deleted"
      redirect_to payment_methods_path
    else
      flash[:danger] = "Something went wrong. Please try again."
      redirect_to payment_methods_path
    end
  end

  private
  
  def payment_method_params
    params.require(:payment_method).permit(:payment_type, :bank, :last_four_digits)
  end

  def authorize_payment_method
    @payment_method = PaymentMethod.find(params[:id])
    unless current_user == @payment_method.user
      flash[:danger] = "You are not authorized to view that page"
      redirect_to dashboard_path
    end
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/edit.html.erb
<div class="page-title">
    <div class="title_left">
      <h3>Payment Methods</h3>
    </div>
  </div>
    
  <div class="clearfix"></div>
    
  <div class="row">
    <div class="col-md-12">
      <div class="x_panel">
        <div class="buttons-row">
          <%= link_to "<i class='fa fa-arrow-left'></i> Back to #{@payment_method.bank} #{@payment_method.last_four_digits}".html_safe, payment_method_path(@payment_method), class: "btn btn-info" %>
        </div>
  
        <div class="x_title">
          <h2>Edit Payment Method</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <%= form_for @payment_method, html: { class: 'form-horizontal form-label-left' } do |f| %>
            <br>
            <div class="form-group">
              <%= f.label :payment_type, class: 'col-md-3 control-label' %>
              <div class="col-md-4">
                <%= f.select :payment_type, ["Debit Card", "Credit Card"], {}, class: 'form-control' %>
              </div>
            </div>
  
            <div class="form-group">
              <%= f.label :bank, class: 'col-md-3 control-label' %>
              <div class="col-md-4">
                <%= f.text_field :bank, class: 'form-control', placeholder: "Bank name" %>
              </div>
            </div>
  
            <div class="form-group">
              <%= f.label :last_four_digits, "Last Four Digits of Card", class: 'col-md-3 control-label' %>
              <div class="col-md-1">
                  <%= f.text_field :last_four_digits, class: 'form-control', placeholder: "xxxx" %>
              </div>
            </div>
  
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-4 col-md-offset-3">
                <%= f.submit "Edit Payment Method", class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/payment_methods/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Payment Methods</h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_content">
        <div class="buttons-row">
          <a href="<%= new_payment_method_path %>" class="btn btn-success">New Payment Method <i class="fa fa-plus"></i></a>
        </div>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Type</th>
              <th>Bank</th>
              <th>Last Four Digits</th>
              <th>Number of Transactions</th>
              <th>Date Added</th>
              <th>Actions</th>
            </tr>
          </thead>
          
          <% @payment_methods.each do |pm| %>
            <tr>
              <!-- ID -->
              <td><%= pm.id %></td>

              <!-- Type -->
              <td><%= pm.payment_type %></td>
              
              <!-- Bank -->
              <td><%= pm.bank %></td>

              <!-- Last 4 Digits -->
              <td><%= ("xx" + pm.last_four_digits) if pm.last_four_digits.present? %></td>

              <!-- Number of Transactions -->
              <td><%= pm.transactions.count %></td>

              <!-- Date Added -->
              <td><%= format_date_with_time(pm.created_at) %></td>
              
              <!-- Actions -->
              <td>
                <div class="btn-group">
                  <%= link_to "View", payment_method_path(pm), class: 'btn btn-info' %>
                  <%  unless pm.payment_type == "Cash" %>
                    <%= link_to "Edit", edit_payment_method_path(pm), class: 'btn btn-warning'%>
                    <%= link_to "Delete", payment_method_path(pm), class: 'btn btn-danger', method: 'delete', data: { confirm: "Are you sure you want to delete this?"} %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>
  

app/views/payment_methods/new.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Payment Methods</h3>
  </div>
</div>
  
<div class="clearfix"></div>
  
<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="buttons-row">
        <%= link_to "<i class='fa fa-arrow-left'></i> Back to Payment Methods".html_safe, payment_methods_path, class: "btn btn-info" %>
      </div>

      <div class="x_title">
        <h2>New Payment Method</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <%= form_for @payment_method, html: { class: 'form-horizontal form-label-left' } do |f| %>
          <br>
          <div class="form-group">
            <%= f.label :payment_type, class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.select :payment_type, ["Debit Card", "Credit Card"], {}, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :bank, class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_field :bank, class: 'form-control', placeholder: "Bank name" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :last_four_digits, "Last Four Digits of Card", class: 'col-md-3 control-label' %>
            <div class="col-md-1">
              <%= f.text_field :last_four_digits, class: 'form-control', placeholder: "xxxx" %>
            </div>
          </div>

          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-4 col-md-offset-3">
              <%= f.submit "Add Payment Method", class: 'btn btn-success'%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/payment_methods/show.html.erb
<div class="page-title">
    <div class="title_left">
      <h3>Payment Methods</h3>
    </div>
  </div>
  
  <div class="clearfix"></div>
  
  <div class="row">
    <div class="col-md-12">
      <div class="x_panel">
        <div class="buttons-row">
          <a href="<%= payment_methods_path %>" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back to Payment Methods</a>

          <% unless @payment_method.payment_type == "Cash" %>
            <div class="btn-group pull-right">
              <%= link_to "Edit", edit_payment_method_path(@payment_method), class: 'btn btn-warning' %>
              <%= link_to "Delete", payment_method_path(@payment_method), class: 'btn btn-danger', method: 'delete', data: { confirm: "Are you sure you want to delete this payment method?"} %>
            </div>
          <% end %>
        </div>
        <div class="x_title">
          <% if @payment_method.payment_type == 'Cash' %>
            <h2>Cash</h2>
          <% else %>
            <h2><%= "ID: #{@payment_method.id} - #{@payment_method.bank} #{@payment_method.last_four_digits}"%></h2>
          <% end %>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <dl class="dl-horizontal">
            <dt>Type</dt>
            <dd><%= @payment_method.payment_type %></dd>

            <% unless @payment_method.payment_type == "Cash" %>
              <dt>Last Four Digits</dt>
              <dd><%= "xx#{@payment_method.last_four_digits}" if @payment_method.last_four_digits.present? %></dd>
            <% end %>
            
            <dt>Date Added</dt>
            <dd><%= format_date_with_time(@payment_method.created_at) %></dd>

            <dt># of Transactions</dt>
            <dd><%= @payment_method.transactions.count %></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Transactions</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <% if @payment_method.transactions.present? %>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Date</th>
                  <th>Name</th>
                  <th>Amount</th>
                  <th>Location</th>
                  <th>Description</th>
                  <th>Category</th>
                  <th>Actions</th>
                </tr>
              </thead>
                
              <% @payment_method.transactions.order(created_at: :desc).each do |t| %>
                <tr>
                  <!-- ID -->
                  <td><%= t.id %></td>
    
                  <!-- Date -->
                  <td><%= t.date %></td>
    
                  <!-- Name -->
                  <td><%= link_to t.name, transaction_path(t) %></td>
    
                  <!-- Amount -->
                  <td class="<%= t.is_expense ? 'text-danger' : 'text-success'%>"><%= "$#{t.amount}" %></td>
    
                  <!-- Location -->
                  <td><%= t.location %></td>
    
                  <!-- Description -->
                  <td><%= t.description %></td>
    
                  <!-- Category -->
                  <td><%= t.category %></td>

                  <!-- Actions -->
                  <td><%= link_to "View", transaction_path(t), class: 'btn btn-info' %></td>
                </tr>
              <% end %>
            </table>
          <% else %>
            <h5>There are no transactions for this payment method</h5>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
    