config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/dashboard' => 'welcome#dashboard', as: :dashboard
  
  resources :users do
    member do
      get 'reset_password', as: :reset_password
      patch 'reset_password' => 'users#update_password'
    end
  end
  resources :payment_methods
  resources :transactions

  get '/login' => 'sessions#new', as: :login
  post '/sessions' => 'sessions#create'

  delete '/logout' => 'sessions#destroy', as: :logout

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate
  before_action :authorize_transaction, only: [:show, :edit]

  def index
    # show transactions of this user
    
    # allow filter for expenses, incomes or all transactions
    @transactions = if params[:type] == 'expenses'
                      @current_user.transactions.where(is_expense: true).order(date: :desc)
                    elsif params[:type] == 'income'
                      @current_user.transactions.where(is_expense: false).order(date: :desc)
                    else
                      @current_user.transactions.order(date: :desc)
                    end
                    
    @remaining_balance = @current_user.remaining_balance
    @expense_this_month = @current_user.transactions.where(date: Date.today.beginning_of_month..Date.today.end_of_month, is_expense: true).sum(:amount) 
    @income_this_month = @current_user.transactions.where(date: Date.today.beginning_of_month..Date.today.end_of_month, is_expense: false).sum(:amount) 
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
    payment_methods = current_user.payment_methods
    @payment_methods_select_options = 
      payment_methods.map do |pm| 
        pm.payment_type == 'Cash' ? ["Cash", pm.id] : ["#{pm.bank} - #{pm.payment_type} (x#{pm.last_four_digits})", pm.id]
      end
    @categories = ["Food", "Groceries", "Transport", "Entertainment", "House", "Shopping", "Services", "Health Care", "Investments", "Salary", "Other"]
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = @current_user

    if @transaction.save
      # update total remaining amount
      update_remaining_balance
      flash[:success] = "Transaction has successfully been created"
      redirect_to transaction_path(@transaction)
    else
      flash[:danger] = "Please check that all fields have been filled in correctly"
      redirect_to new_transaction_path
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    payment_methods = @current_user.payment_methods
    @payment_methods_select_options = 
    payment_methods.map do |pm| 
      pm.payment_type == 'Cash' ? ["Cash", pm.id] : ["#{pm.bank} - #{pm.payment_type} (x#{pm.last_four_digits})", pm.id]
    end
    @categories = ["Food", "Groceries", "Transport", "Entertainment", "House", "Shopping", "Services", "Health Care", "Investments", "Salary", "Other"]
  end

  def update
    @transaction = Transaction.find(params[:id])

    if @transaction.update(transaction_params)
      # update total remaining amount
      update_remaining_balance
      flash[:success] = "Transaction has successfully been updated"
      redirect_to transaction_path(@transaction)
    else
      flash[:danger] = "Please check that all fields have been filled in correctly"
      redirect_to edit_transaction_path(@transaction)
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    if @transaction.destroy
      # update total remaining amount
      update_remaining_balance_for_destroy
      flash[:warning] = "Successfully deleted transaction"
      redirect_to transactions_path
    else
      flash[:danger] = "Something went wrong. Please try again."
      redirect_to transactions_path
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount, :name, :location, :description, :date, :category, :is_expense, :payment_method_id)
  end

  def authorize_transaction
    @transaction = Transaction.find(params[:id])
    unless current_user == @transaction.user
      flash[:danger] = "You are not authorized to view that page"
      redirect_to dashboard_path
    end
  end

  def update_remaining_balance
    new_balance = @transaction.is_expense ? current_user.remaining_balance - @transaction.amount : current_user.remaining_balance + @transaction.amount
    @current_user.update_columns(remaining_balance: new_balance)
  end

  def update_remaining_balance_for_destroy
    new_balance = @transaction.is_expense ? current_user.remaining_balance + @transaction.amount : current_user.remaining_balance - @transaction.amount
    @current_user.update_columns(remaining_balance: new_balance)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Transactions</h3>
  </div>
</div>
    
<div class="clearfix"></div>
    
<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="buttons-row">
        <%= link_to "<i class='fa fa-arrow-left'></i> Back to Transaction ID: #{@transaction.id}".html_safe, transaction_path(@transaction), class: "btn btn-info" %>
      </div>

      <div class="x_title">
        <h2>Edit Transaction</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <%= form_for @transaction, html: { class: 'form-horizontal form-label-left' } do |f| %>
          <br>
          <div class="form-group">
            <%= f.label :amount, "Amount*", class: 'col-md-3 control-label' %>
            <div class="col-md-2">
              <span class="fa fa-dollar form-control-feedback left" aria-hidden="true"></span>
              <%= f.text_field :amount, class: 'form-control text-center' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :name, "Name*", class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :location, class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_field :location, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :description, class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :category, "Category", class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.select :category, @categories, {}, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :payment_method_id, "Payment Method", class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.select :payment_method_id, @payment_methods_select_options, {}, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :date, class: 'col-md-3 control-label' %>
            <div class="col-md-2">
              <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
              <%= f.text_field :date, readonly: true, class: 'form-control text-center', id: 'date', :value=> @transaction.date.strftime("%d/%m/%YYYY") %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :is_expense, 'Transaction Type', class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <div class="btn-group">
                <button type="button" class="btn btn-default" id="expenseButton">
                  <%= f.radio_button :is_expense, true, checked: true, class: 'form-control', id: 'expenseRadio', style: 'display: none;' %>
                  Expense
                </button>
                <button type="button" class="btn btn-default" id="incomeButton">
                  <%= f.radio_button :is_expense, false, class: 'form-control', id: 'incomeRadio', style: 'display: none;' %>
                  Income
                </button>
              </div>
            </div>
          </div>
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-4 col-md-offset-3">
              <%= f.submit "Edit Transaction", class: "btn btn-success"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  
<%= javascript_include_tag 'transaction_form' %>

app/views/transactions/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Transactions</h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row tile_count">
  <div class="col-md-4 tile_stats_count">
    <span class="count_top">
      <i class="fa fa-square"> Remaining Balance</i>
    </span>
    <div class="count <%= @remaining_balance <= 0.0 ? 'red' : 'green' %>"><%= format_amount_with_commas(@remaining_balance) %></div>
  </div>
  <div class="col-md-4 tile_stats_count">
    <span class="count_top">
      <i class="fa fa-minus-square-o"> Expenses This Month</i>
    </span>
    <div class="count red"><%= format_amount_with_commas(@expense_this_month) %></div>
  </div>
  <div class="col-md-4 tile_stats_count">
    <span class="count_top">
      <i class="fa fa-plus-square"> Income This Month</i>
    </span>
    <div class="count green"><%= format_amount_with_commas(@income_this_month) %></div>
  </div>
</div>  

<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_content">
        <div class="buttons-row">
          <a href="<%= new_transaction_path %>" class="btn btn-success">New Transaction <i class="fa fa-plus"></i></a>
        </div>
          <ul class="nav nav-tabs">
            <li role="presentation" class="<%= 'active' unless params[:type].present? %>"><%= link_to "All", transactions_path %></li>
            <li role="presentation" class="<%= 'active' if params[:type] == 'expenses' %>"><%= link_to "Expenses", transactions_path(type: 'expenses') %></li>
            <li role="presentation" class="<%= 'active' if params[:type] == 'income' %>"><%= link_to "Income", transactions_path(type: 'income') %></li>
          </ul> 
          
        <% if @transactions.present? %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Date</th>
                <th>Name</th>
                <th>Amount</th>
                <th>Payment Method</th>
                <th>Location</th>
                <th>Description</th>
                <th>Category</th>
                <th>Actions</th>
              </tr>
            </thead>
            
            <% @transactions.each_with_index do |t, index| %>
              <tr>
                <!-- ID -->
                <td><%= index + 1 %></td>

                <!-- Date -->
                <td><%= format_date(t.date) %></td>

                <!-- Name -->
                <td><%= link_to t.name, transaction_path(t) %></td>

                <!-- Amount -->
                <td class="<%= t.is_expense ? 'text-danger' : 'text-success'%>"><%= format_amount(t.amount) %></td>

                <!-- Payment Method -->
                <td><%= t.payment_method.payment_type.downcase == 'cash' ? "Cash" : "#{t.payment_method.bank} #{t.payment_method.last_four_digits}" %></td>

                <!-- Location -->
                <td><%= t.location %></td>

                <!-- Description -->
                <td><%= t.description %></td>

                <!-- Category -->
                <td><%= t.category %></td>

                <!-- Actions -->
                <td>
                  <div class="btn-group">
                    <%= link_to 'View', transaction_path(t), class: 'btn btn-info' %>
                    <%= link_to 'Edit', edit_transaction_path(t), class: 'btn btn-warning' %>
                    <%= link_to 'Delete', transaction_path(t), class: 'btn btn-danger', method: 'delete', data: { confirm: "Are you sure you want to delete this transaction?" } %>
                  </div>
                </td>
              </tr>
            <% end %>
          </table>
        <% else %>
          <h4>There are no transactions. Add a new one <%= link_to "here", new_transaction_path, style: 'text-decoration: underline' %></h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Transactions</h3>
  </div>
</div>
  
<div class="clearfix"></div>
  
<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="buttons-row">
        <%= link_to "<i class='fa fa-arrow-left'></i> Back to Transactions".html_safe, transactions_path, class: "btn btn-info" %>
      </div>

      <div class="x_title">
        <h2>New Transaction</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <%= form_for @transaction, html: { class: 'form-horizontal form-label-left' } do |f| %>
          <br>
          <div class="form-group">
            <%= f.label :amount, "Amount*", class: 'col-md-3 control-label' %>
            <div class="col-md-2">
              <span class="fa fa-dollar form-control-feedback left" aria-hidden="true"></span>
              <%= f.text_field :amount, class: 'form-control text-center' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :name, "Name*", class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :location, class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_field :location, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :description, class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :category, "Category", class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.select :category, @categories, {}, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :payment_method_id, "Payment Method", class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <%= f.select :payment_method_id, @payment_methods_select_options, {}, class: 'form-control' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :date, class: 'col-md-3 control-label' %>
            <div class="col-md-2">
              <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
              <%= f.text_field :date, readonly: true, class: 'form-control text-center', id: 'date' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :is_expense, 'Transaction Type', class: 'col-md-3 control-label' %>
            <div class="col-md-4">
              <div class="btn-group">
                <button type="button" class="btn btn-default" id="expenseButton">
                  <%= f.radio_button :is_expense, true, checked: true, class: 'form-control', id: 'expenseRadio', style: 'display: none;' %>
                  Expense
                </button>
                <button type="button" class="btn btn-default" id="incomeButton">
                  <%= f.radio_button :is_expense, false, class: 'form-control', id: 'incomeRadio', style: 'display: none;' %>
                  Income
                </button>
              </div>
            </div>
          </div>
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-4 col-md-offset-3">
              <%= f.submit "Add Transaction", class: "btn btn-success"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'transaction_form' %>

app/views/transactions/show.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>
      Transactions
      <small class="<%= @transaction.is_expense ? 'text-danger' : 'text-success'%>">
        <%= @transaction.is_expense ? "Expense" : "Income" %>
      </small>
    </h3>
  </div>
</div>

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="buttons-row">
        <a href="<%= transactions_path %>" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back to Transactions</a>

        <div class="btn-group pull-right">
          <%= link_to "Edit", edit_transaction_path(@transaction), class: 'btn btn-warning' %>
          <%= link_to "Delete", transaction_path(@transaction), class: 'btn btn-danger', method: 'delete', data: { confirm: "Are you sure you want to delete this transaction?"} %>
        </div>
      </div>
      <div class="x_title">
        <h2><%= "ID: #{@transaction.id} - #{@transaction.name}" %></h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <dl class="dl-horizontal">
          <dt>Transaction Type</dt>
          <dd class="<%= @transaction.is_expense ? 'text-danger' : 'text-success'%>"><%= @transaction.is_expense ? "Expense" : "Income" %></dd>

          <dt>Amount</dt>
          <dd class="<%= @transaction.is_expense ? 'text-danger' : 'text-success'%>"><%= format_amount(@transaction.amount) %></dd>

          <dt>Location</dt>
          <dd><%= @transaction.location %></dd>

          <dt>Description</dt>
          <dd><%= @transaction.description %></dd>

          <dt>Category</dt>
          <dd><%= @transaction.category %></dd>

          <dt>Date</dt>
          <dd><%= format_date(@transaction.date) %></dd>

          <div class="ln_solid"></div>
          <dt>Payment Method</dt>
          <dd><%= link_to format_payment_method(@transaction.payment_method), payment_method_path(@transaction) %></dd>
        </dl>
      </div>
    </div>
  </div>
</div>