config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/dashboard' => 'welcome#dashboard', as: :dashboard
  
  resources :users do
    member do
      get 'reset_password', as: :reset_password
      patch 'reset_password' => 'users#update_password'
    end
  end
  resources :payment_methods
  resources :transactions

  get '/login' => 'sessions#new', as: :login
  post '/sessions' => 'sessions#create'

  delete '/logout' => 'sessions#destroy', as: :logout

end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="pull-right">
    &copy; Pocket Trackr 2017 - <%= link_to "Chakrit Prasatwattana", "https://github.com/chakritp", target: "_blank" %>
  </div>
  <div class="clearfix"></div>
</footer>

app/views/layouts/_gentelella_flash.html.erb
<% flash.each do |key, value| %>
<div class="flash alert alert-<%= key %> alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  <%= value %>
</div>
<% end %>

app/views/layouts/_header.html.erb
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="<%= @avatar_url %>" alt=""><%= "#{current_user.first_name} #{current_user.last_name}"%>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li>
              <%= link_to "My Settings", user_path(current_user.id) %>
            </li>
            <li><a href="<%= logout_path %>" data-method="delete" ><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
  <%= render 'layouts/gentelella_flash' %>
</div>

app/views/layouts/_sidebar.html.erb
<!-- left nav -->
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="<%= dashboard_path %>" class="site_title"><i class="fa fa-money"></i> <span>Pocket Trackr</span></a>
    </div>
    
    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <img src="<%= @avatar_url %>" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2><%= "#{current_user.first_name} #{current_user.last_name}"%></h2>
      </div>
    </div>
    <!-- /menu profile quick info -->
    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
          <!-- Home -->
          <li><a href="<%= dashboard_path %>"><i class="fa fa-home"></i> Home</span></a></li>

          <!-- All Transaction -->

          <li><a><i class="fa fa-list"></i> Transactions <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><%= link_to "View Transactions", transactions_path %></li>
                <li><%= link_to "Add Transaction +", new_transaction_path %></li>
            </ul>
          </li>
          
          <!-- Expenses -->
          <!-- <li><a><i class="fa fa-minus-square"></i> Expenses <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a>View Expenses</a></li>
              <li><a>Add Expense <i class="fa fa-plus"></i></a></li>
            </ul>
          </li> -->

          <!-- Income -->
          <!-- <li><a><i class="fa fa-plus-square"></i> Income <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a>View Income</a></li>
              <li><a>Add Income <i class="fa fa-plus"></i></a></li>
            </ul>
          </li> -->

          <!-- Payment Methods -->
          <li><a><i class="fa fa-credit-card"></i> Payment Methods <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to "View Payment Methods", payment_methods_path %></li>
              <li><%= link_to "Add Payment Method +", new_payment_method_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PocketTrackr</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- Left Nav -->
        <%= render 'layouts/sidebar' %>

        <!-- Header -->
        <%= render "layouts/header" %>

        <!-- page content -->
        <div class="right_col" role="main" style="min-height: 100vh;">
          <div>
            <%= yield %>
          </div>
        </div>
        <!-- / page content -->

        <!-- footer content -->
        <%= render "layouts/footer"%>
      </div>
    </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>PocketTrackr</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <%= stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <div class="masthead clearfix">
          <div class="inner">
            <%= link_to root_path do %>
              <h3 class="masthead-brand">Pocket Trackr</h3>
            <% end %>
            <nav class="nav nav-masthead">
              <%= link_to 'Home', root_path, class: "nav-link #{'active' if params[:controller] == 'welcome' && params[:action] == 'index'}" %>
              <%= link_to 'Log In', login_path, class: "nav-link #{'active' if params[:controller] == 'sessions' && params[:action] == 'new'}" %>
              <%= link_to 'Sign Up', new_user_path, class: "nav-link #{'active' if params[:controller] == 'users' && params[:action] == 'new'}" %>
            </nav>
          </div>
          <%= render 'layouts/flash' %>
        </div>
        
        <%= yield %>

        <div class="mastfoot">
          <div class="inner">
            &copy; Pocket Trackr 2017 - <%= link_to "Chakrit Prasatwattana", "https://github.com/chakritp", target: "_blank" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>